# Generated by Django 5.1.6 on 2025-02-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_id', models.CharField(blank=True, max_length=145, null=True, verbose_name='连接ID')),
                ('connect_name', models.CharField(blank=True, max_length=145, null=True, verbose_name='连接名称')),
                ('sql_type', models.CharField(blank=True, choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('sqlserver', 'SQL Server')], max_length=145, null=True, verbose_name='数据库类型')),
                ('host', models.CharField(blank=True, max_length=145, null=True, verbose_name='主机地址')),
                ('port', models.CharField(blank=True, max_length=145, null=True, verbose_name='端口')),
                ('db', models.CharField(blank=True, max_length=145, null=True, verbose_name='数据库名')),
                ('username', models.CharField(blank=True, max_length=145, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=145, null=True, verbose_name='密码')),
                ('uri', models.CharField(blank=True, max_length=145, null=True, verbose_name='连接URI')),
                ('connect_status', models.CharField(blank=True, choices=[('normal', '正常'), ('abnormal', '异常')], max_length=145, null=True, verbose_name='连接状态')),
                ('create_user', models.CharField(blank=True, max_length=145, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '数据库连接信息',
                'verbose_name_plural': '数据库连接信息管理',
                'db_table': 'dt_connection_info',
                'ordering': ['-update_time'],
            },
        ),
    ]
