# Generated by Django 5.1.6 on 2025-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('mock_type', models.CharField(choices=[('sql', 'SQL'), ('api', 'API'), ('file', 'File')], max_length=50, verbose_name='造数类型')),
                ('sql_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('sqlserver', 'SQL Server')], max_length=50, verbose_name='数据库类型')),
                ('is_increment_schema', models.BooleanField(default=False, verbose_name='是否新建数据库')),
                ('is_increment_table', models.BooleanField(default=False, verbose_name='是否新建表')),
                ('schema_name', models.CharField(max_length=145, verbose_name='数据库名')),
                ('table_name', models.CharField(max_length=145, verbose_name='表名')),
                ('is_increment_data', models.BooleanField(default=True, verbose_name='是否插入数据')),
                ('increment_lines', models.IntegerField(verbose_name='插入行数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '造数历史记录',
                'verbose_name_plural': '造数历史记录管理',
                'db_table': 'dt_mock_history',
                'ordering': ['-create_time'],
            },
        ),
    ]
