# Generated by Django 5.1.6 on 2025-02-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('TEST', '测试环境'), ('PROD', '生产环境')], max_length=10, verbose_name='环境')),
                ('of_business', models.CharField(max_length=50, verbose_name='所属业务')),
                ('host', models.CharField(max_length=100, verbose_name='域名地址')),
                ('api_name', models.CharField(max_length=100, verbose_name='API名称')),
                ('api_path', models.CharField(max_length=200, verbose_name='API路径')),
                ('req_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10, verbose_name='请求方法')),
                ('req_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('body_type', models.CharField(choices=[('JSON', 'JSON'), ('DATA', 'Form Data'), ('PARAMS', 'params'), ('RAW', 'Raw')], max_length=10, verbose_name='请求体类型')),
                ('req_header', models.TextField(blank=True, null=True, verbose_name='请求头')),
                ('req_params', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('resp_demo', models.TextField(blank=True, null=True, verbose_name='响应示例')),
                ('extr_value', models.TextField(blank=True, null=True, verbose_name='提取值')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API信息',
                'verbose_name_plural': 'API信息列表',
                'db_table': 'api_info',
            },
        ),
    ]
