# Generated by Django 5.1.6 on 2025-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('label', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_base_menu', models.BooleanField(default=False, verbose_name='是否为基础菜单')),
                ('sub_menu', models.CharField(blank=True, max_length=200, null=True, verbose_name='子菜单')),
                ('path', models.CharField(max_length=100, verbose_name='路由路径')),
                ('name', models.CharField(max_length=50, verbose_name='路由名称')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='外部链接')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单管理',
                'db_table': 'menu',
                'ordering': ['menu_id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('role_permissions', models.TextField(blank=True, null=True, verbose_name='角色权限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('tips', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色管理',
                'db_table': 'role',
                'ordering': ['role_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='用户标识')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('roles', models.CharField(blank=True, max_length=200, null=True, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
                'db_table': 'user',
                'ordering': ['-create_time'],
            },
        ),
    ]
