# Generated by Django 5.1.6 on 2025-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('PC', 'pc'), ('APP', 'app')], max_length=10, verbose_name='设备大类')),
                ('os_name', models.CharField(max_length=50, verbose_name='操作系统')),
                ('os_version', models.CharField(max_length=20, verbose_name='操作系统版本')),
                ('device_model', models.CharField(max_length=50, verbose_name='手机型号')),
                ('asset_code', models.CharField(max_length=20, unique=True, verbose_name='资产编码')),
                ('screen_lock_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='锁屏密码')),
                ('install_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='安装密码')),
                ('processor', models.CharField(max_length=50, verbose_name='芯片处理器')),
                ('owner', models.CharField(max_length=50, verbose_name='所属人')),
                ('current_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='领用人')),
                ('used_days', models.IntegerField(default=0, verbose_name='占用时间（天）')),
                ('status', models.CharField(choices=[('0', '空闲'), ('1', '占用'), ('2', '申请中')], max_length=20, verbose_name='设备状态')),
                ('buy_time', models.DateField(verbose_name='购入年份')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备列表',
                'db_table': 'devices',
            },
        ),
    ]
