# Generated by Django 5.1.6 on 2025-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceMng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PC', 'PC'), ('APP', 'APP')], max_length=10, verbose_name='设备大类'),
        ),
    ]
