# Generated by Django 5.1.6 on 2025-02-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceMng', '0002_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='holding_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始占用时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PC', 'PC'), ('APP', 'APP'), ('PHONE', '手机'), ('PAD', '平板')], max_length=10, verbose_name='设备大类'),
        ),
        migrations.AlterField(
            model_name='device',
            name='used_days',
            field=models.IntegerField(default=0, verbose_name='占用天数（天）'),
        ),
        migrations.CreateModel(
            name='DeviceApply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_user', models.CharField(max_length=50, verbose_name='申请人')),
                ('device_asset_code', models.CharField(max_length=20, verbose_name='设备资产编码')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approval_status', models.CharField(choices=[('0', '待审批'), ('1', '审批通过'), ('2', '审批拒绝')], default='0', max_length=10, verbose_name='审批状态')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='审批人')),
                ('approval_comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('apply_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deviceMng.device', verbose_name='申请设备')),
            ],
            options={
                'verbose_name': '设备申请',
                'verbose_name_plural': '设备申请管理',
                'db_table': 'device_apply',
                'ordering': ['-apply_time'],
            },
        ),
    ]
