# Generated by Django 5.1.6 on 2025-02-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceMng', '0003_device_holding_time_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceapply',
            name='apply_device',
            field=models.CharField(max_length=50, verbose_name='申请设备'),
        ),
    ]
