# Generated by Django 5.1.6 on 2025-02-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceMng', '0004_alter_deviceapply_apply_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='buy_time',
            field=models.DateField(blank=True, null=True, verbose_name='购入年份'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS'), ('Mac', 'Mac'), ('Windows', 'Windows'), ('other', '其他')], max_length=10, verbose_name='设备大类'),
        ),
    ]
