# Generated by Django 5.1.6 on 2025-02-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceMng', '0005_alter_device_buy_time_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS'), ('Mac', 'Mac'), ('Windows', 'Windows'), ('harmonyOS', 'HarmonyOS'), ('other', '其他')], max_length=10, verbose_name='设备大类'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('0', '空闲'), ('1', '占用'), ('2', '申请中')], default='0', max_length=20, verbose_name='设备状态'),
        ),
    ]
